name = "chatgpt-weixin-worker"
main = "src/index.ts"
compatibility_date = "2023-03-10"

[[kv_namespaces]]
binding = "KV"
id = "<Your KV ID>"

[[d1_databases]]
binding = "D1"
database_name = "chatgpt-weixin-worker"
database_id = "<Your d1 database id>"

[triggers]
crons = ["0 * * * *"]

[vars]
WEIXIN_APP_ID = "<Your weixin appid>"
WEIXIN_SECRET = "<Your weixin secret>"
OPENAI_API_KEY = "<Your chatgpt api key>"
